### ISSUE TITLE
RR API change

### ISSUE THREAD

**Issue by kanadaj** [fake-name/wlnupdates#652]
Hey fake-name,

Just noticed the _slug-fest_ on WLN Updates, just giving you a heads-up that the API has been updated to contain the slugs for all chapters! If you don't have the slugs for older chapters, please use the link `/fiction/chapter/{chapterid}`, this will redirect to the correct slug without messing with our SEO >_< The above link will keep working indefinitely. I didn't want to enforce slug redirects since it might get messy very quickly with redirect loops what with all the terrible browser implementations out there...

**Comment by fake-name** [comment]
Heh, I was wondering if that would ever get noticed. 

I'll fix this when I have time.

**Comment by fake-name** [comment]
I don't know if you've [noticed this](https://github.com/fake-name/ReadableWebProxy/blob/master/WebMirror/OutputFilters/RoyalRoadL/RRLJsonXmlSeriesUpdateFilter.py#L48-L52).

Basically, the RRL API isn't helping reduce page load, since I still need to make normal HTTP API requests to get some missing information (`ratingValue` and `ratingCount`). I brought this up when you initially provided the API, but I think it might have been lost.

**Comment by kanadaj** [comment]
I'll add those to the fiction info endpoint in a minute

**Comment by kanadaj** [comment]
Aaand the patch is out. No fields on the Info endpoint: authorId, authorName, ratingCount, ratingValue

**Comment by fake-name** [comment]
Sweet!

**Comment by fake-name** [comment]
Ok, I'm completely API only at this point. 

Thanks!

**Comment by fake-name** [comment]
I've now pushed a change that should rewrite all existing URLs to use the new format.
