### ISSUE TITLE
Please add 4 default states: Reading, Read, Plan To Read and Dropped

### ISSUE THREAD

**Issue by Emasoft** [fake-name/wlnupdates#715]
Currently there is only 1 default reading list:
- Not Watched (...it should be 'Unread' maybe?)

The user has to manually create new reading lists categories for tracking its reading progress. This is encoumbering for the  users and also creates a mess of non standard names that cannot be used by epub readers or website trackers to synch with WLNUpdates in a consistent way. 

To solve this problem I suggest to add the following default reading lists:
- Plan To Read
- Reading
- Dropped
- Read

A novel can only be placed in one of the above lists, and adding it to a different list would automatically remove it from the previous one, reflecting their changed status. The user can optionally create other lists for special purposes, but those default ones should be not deletable. This, paired the existing option to mark the single chapters as read or unread, would make WLNUpdates easier to use as a tracking website. Some time ago I tried to convince the novelupdates guys about adding this features (here you can read the [thread](https://forum.novelupdates.com/threads/add-3-default-reading-list-to-read-dropped-read.119342/)) but they seem to be very miopic in this regard. They do not even bother with an API after all, so they must not be interested in this. 
WLNUpdates instead is very API oriented and it could easily become a central tracker for all light novels sites and epub readers. You can also add this 4 states directly into the API, so that epub readers apps can use WLNUpdates as an online tracker to keep their progress status safe online and portable from mobile epub readers to desktop epub readers without having to manually migrate all reading statuses every time you switch platform. This would make WLNUpdates as popular as sites like MyAnimeList (most people uses MAL to track their online manga reading progress using [Malsync](https://malsync.moe/)).
Please implement the 4 default reading lists as a standard for all users, similarly to any tracker websites (see for example: [MAL](https://myanimelist.net/manga/13/One_Piece)).

**Comment by fake-name** [comment]
Setting a series to `<not watched>` _removes_ the item in question from any reading list. It's not really a list per-se.

While I'm fully open to adding some sensible default list names, I'm not sure how the idea of default reading lists would interact with the ability to create custom lists. I use _lots_ of lists personally for sorting and categorization and being restricted to just 4 default lists would break a substantial portion of the utility of lists in the first place, at least for me. 

Note that the way reading lists are currently implemented actually supports this use case from a API standpoint already. Effectively, reading lists are basically a tag that a user can apply to each series. The contents of the tag are a free-form string, and the only thing done with it server-side at all is using it to sort series into list groups. 

Therefore, lists don't _really_ exist, but rather they're a grouping tag. As such, default lists could be trivially implemented by any application that needs them, since applying a list (tag) name to a series will create the list if it doesn't exist. If there are no items with a specific list name attached to them, the list therefore doesn't exist. 

As a result, this is basically 100% something that would only exist client-side, so short of something like having suggested list names if a user has no lists at all (which is a neat idea!), I'm not sure what changes I could actually make here.

**Comment by Emasoft** [comment]
Just add the 4 undeletable lists, and everything will work fine. Believe me. All tracking sites works that way.
Since behind the scene it is just a tag, you should create a special rule when adding a tag:
- if the tag belong to the default group of tags, remove any other tag that belong to the default group before adding this tag to the novel.
- if the tag doesn't belong to the default group of tags, then just add the tag to the novel.

**Comment by fake-name** [comment]
The reading list entry for each series can only have a single value. Series cannot be in multiple lists already. 

I'm not interested in limiting the reading list system to only 4 lists. That would make it useless to me, and from the linked novelupdates forum I'm very much not the only person who uses reading lists this way.

Lists cannot be undeletable, since if there are no items tagged with a specific list name, that list doesn't exist.

**Comment by fake-name** [comment]
Can you clarify what you're arguing for? Are you saying there should only be 4 possible lists (the ones you've enumerated)? 

Or are you arguing there should be some available default list names, but other list names are fine.

**Comment by Emasoft** [comment]
Let me make an example: a novel with a "Completed" status (arbitrary custom naming by user X) on WLNUpdates would not be imported in the app as a "Read", because the app doesn't know that custom naming meaning, and it would revert to 'unread'.
So when the user is going to synch back from the app to WLNUpdates, the novel would be tagged as 'unread'.
This is why you need CONSISTENCY in naming those 4 reading states.

**Comment by fake-name** [comment]
Again:

Can you clarify what you're arguing for? Are you saying there should only be 4 possible lists (the ones you've enumerated)? Or are you arguing there should be some available default list names, but other list names are fine?

**Comment by Emasoft** [comment]
There sould be those 4 default lists.
Optionally the user can create other custom lists.

**Comment by fake-name** [comment]
You're missing the point that **lists do not exist without any items on them**. 

I can have _client-side_ convenience facilities to make it easier to people to choose some list name, bit the lists still won't exist until there's stuff on them. 

So if some application is trying to synchronize lists _from_ wlnupdates, it'll get only the lists with items on it, since they're the only lists that actually exist. 

If an application is trying to synchronize lists _into_ wlnupdates, any list that doesn't exist will be created on-the-fly due to how the lists are actually implemented.

**Comment by Emasoft** [comment]
Why? If lists are just tags, then tags can exist indipendently as a list of strings and be assigned to novels or not.

**Comment by fake-name** [comment]
Because they kind of act _like_ tags, but the [internal implementation is different](https://github.com/fake-name/wlnupdates/blob/master/app/models.py#L839). Effectively it's a free-form string that's used for watch grouping and nothing else. 

For extremely large numbers of watched series, it's not the most efficient way to implement it, but it seems to work fine for watching more then 2K items without a substantial performance impact at the moment. 

I considered using a many-to-many mapping table for watch lists, but that would add a bunch of complexity for not much improvement.

**Comment by Emasoft** [comment]
You don't need to implement a real many-to-many db. You just need to mask it as such in the UI and in the API. 
For example when a query comes to check the "Plan To Read" list, the API just check if the "Plan To Read" string exists in a separated list of existing tags before checking if any novel is tagged as such. Every user profile just need two tables:
1 - list of existing tags
2 - table of novels with reading lists (2 columns: novel id, tags separated by comma)
Of course you also need a global list of the 4 default tags, shared by all users.

**Comment by fake-name** [comment]
All of this seems to be working around what is basically just websites that would try to sync with the site doing that in a really, **really** stupid manner.

I'm not really seeing a compelling reason to bend over backwards to deal with _other_ applications being shit.

**Comment by fake-name** [comment]
I'd certainly be open to a refactor of the reading-list system, but it's not something I'd be interested in pursuing myself. 

PR's welcome, though!

**Comment by Emasoft** [comment]
Tell me then: I use 3 different epub readers every day, on 3 different platforms (pc, ipad, android phone). Those 3 different epub readers have 3 different sets of status names. Not one is congruent. One is 'completed', another is 'read', and the last is 'finished'. 
I need a central tracker on the cloud like WLNUpdate to synch those 3 apps and keep my epubs status updated and consistent independently of the platform. 
So, what would happen if I let the apps create the tags names when it synch for the first time? Every app would create 4 different tags for a total of 12 different reading lists. A mess. Don't you think this is far more stupid that the standardized solution above, adopted by tracking sites like MAL?

**Comment by fake-name** [comment]
Maybe the 4 apps shouldn't predefine _any_ list names, so they all synchronize cleanly and don't duplicate anything.

**Comment by Emasoft** [comment]
How can an epub reading app do that? All users expect the app to automatically detect if a novel is currently being read or finished, and what chapter the user currently is. It is a basic functionality. The user is never even asked to select them, even less to give such statuses names. They are predefined. And even if in some rare app they are customizable, this would make things even worse, because the names would be arbitrary choosen by the user, and when he happens to switch to another app it would be already configured in a different way and correcting it would create issues. Not to mention the fact that the users are lazy and will never do it, even the slightest error in spelling ("Reading" instead of "reading") would result in a massive loss of data. Why to make things so complicated? Consistency is a basic principle of good design. Why are you so against it?

**Comment by fake-name** [comment]
> How can an epub reading app do that? All users expect the app to automatically detect if a novel is currently being read or finished, and what chapter the user currently is.

Neither of these have anything to do with lists. I have about 20 lists that track things I'm currently reading, in different groupings/genres. Just because having a single reading list works _for you_ doesn't make it work for everyone.

If custom list names synchonize properly (e.g. applications don't have dumb limits on them), literally everything you described above would work without issue. You have the lists _you_ set up, and they'd be available everywhere exactly as you expect them.

The one case where I can see some value in special-casing things is a list for "finished" items, entirely to make it sort differently, other then that trying to force one person's idea of how they should organize their reading progress on everyone else to just seem stupid.

**Comment by Emasoft** [comment]
I guess you don't realize the issue from an average user stand point. Let me ask you this: how many registered users on WLNUpdates have created such 4 basic statuses (indipendently from how they called them) and actually uses those to track the novels they are reading? I'm pretty sure that they are a very small percentage, because having to customize manually something that can be automatic or predefined it is annoying.

**Comment by fake-name** [comment]
That's an argument for a few template list names, and not much else.

Really, if you're saying that having to name a watch list is too complicated for your average person, trying to deal with multi-site synchronization is basically rocket surgery at that point. 

So are you arguing _for_  advanced features, or against them?

**Comment by sebbu2** [comment]
I currently have 15 lists, that i separate according from categories like Emasoft. Mine are :

reading (currently),
original (only on webnovel, because some sites separated translations and original english language),
on-hold (i stopped reading it temporary),
dropped (i stopped reading definitively/for a long time),
stalled (i haven't stopped reading it, but the author/translator stopped releasing. i could separate this in 2 if raw & translation have different status),
completed (all read),
plan to read (i'll start it soon)

I also separate webnovel/qidian from other sites for reading (wonder what to do for releases on multiple sites, i might add scribblehub too)

I'm also using another software (my own) to fill & update my lists, it works perfectly with it : it get added into reading or original according to the tag, it only notify me for reading/original/stalled, and updating... doesn't care which list it's from.
It might move into complete once i know it's complete and i've read everything, might recognize hiatus/stalled according to chapters releases dates, etc...

I don't see any issue apart from the novel on multiple list when there's one entry for all site the novel is on (sometimes it's the same entry, sometimes not, sometimes there's differences in the released chapters according to platform, or time difference between the releases).

**Comment by Emasoft** [comment]
Is your tracking software this one?
https://github.com/sebbu2/LN-backup-sync
It's great, but it only works with the Moon reader android app. I'm trying to write something similar for KyBook 3 on iOS, but due to the iOS writing restrictions on the app files I need some help from the author (   https://github.com/kolyvan  ), but he is not answering my emails.
About the watch list categories, the 4 basic ones are in your synch script too, and that is the important thing. Additional custom categories are optional and always welcome, but I still think that to ensure basic functionality any tracking website API should define the 4 basic states as mandatory for ensuring minimal interoperability without user intervention.

**Comment by sebbu2** [comment]
It is this one, i could support others (i recently updated the README), but only a few supports cloud sync / to dropbox or googledrive. Bookfusion and amazon kindle have a web sync i could use. Others might require root / jailbreak to modify the files where the pos is stored.
